# This file generates the GitHub Actions matrix.
# 構成: 左手 = 4way スティック（Peripheral） / 右手 = トラックボール（Central）
# 他の構成（non-trackball など）は git 履歴を参照
---
include:
  - board: xiao_ble//zmk
    shield: lism_left rgbled_adapter
    snippet: 4waystick-peripheral
    artifact-name: lism_left_peripheral_4waystick
  - board: xiao_ble//zmk
    shield: lism_right rgbled_adapter
    snippet: trackball-central
    artifact-name: lism_right_central_trackball
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
  - board: xiao_ble//zmk
    shield: lism_right rgbled_adapter
    artifact-name: lism_right_central_trackball_studio
    snippet: "studio-rpc-usb-uart trackball-central"
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

  # Reset
  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: settings_reset-seeeduino_xiao_ble-zmk
